# Generated by Django 3.1.2 on 2021-02-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('passward', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('movie1', models.CharField(max_length=100)),
                ('movie2', models.CharField(max_length=100)),
                ('movie3', models.CharField(max_length=100)),
            ],
        ),
    ]
