# Generated by Django 3.1.2 on 2021-02-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210228_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='twitter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
