# Generated by Django 3.1.7 on 2021-03-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_usermodel_twitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='movie1_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='movie2_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='movie3_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
